name: Deploy Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/743518400007/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-deployer@finance-data-pipeline-489121.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy bitcoin-pipeline \
            --source ./cloud_run \
            --region us-west1 \
            --allow-unauthenticated